default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  user: <%= ENV.fetch("POSTGRES_USER") { "maybe_user" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "maybe_123" } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "sure_production" } %>
